# Generated by Django 3.1.5 on 2021-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0005_auto_20210218_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', '현금'), ('card', '카드')], max_length=20, verbose_name='결제구분'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('done', '완료'), ('ord', '주문'), ('prep', '준비중')], max_length=20, verbose_name='완료여부'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='jobtitle',
            field=models.CharField(choices=[('J50', '아르바이트'), ('J20', '메니저'), ('J10', 'CEO'), ('J40', '인턴'), ('J30', '사원')], max_length=20, verbose_name='직급'),
        ),
    ]
