# Generated by Django 3.1.6 on 2021-02-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapleApp', '0006_auto_20210203_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(max_length=100)),
                ('mp_price', models.IntegerField(default=0)),
                ('mp_count', models.IntegerField(default=0)),
            ],
        ),
    ]
